# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-07-03 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190703_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_move',
            field=models.IntegerField(null=True),
        ),
    ]
